// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/feed.ts";
import * as $1 from "./routes/index.jsx";
import * as $$0 from "./islands/FeedList.jsx";
import * as $$1 from "./islands/InputBar.jsx";

const manifest = {
  routes: {
    "./routes/feed.ts": $0,
    "./routes/index.jsx": $1,
  },
  islands: {
    "./islands/FeedList.jsx": $$0,
    "./islands/InputBar.jsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
